services:
  elasticsearch:
    build: .
    image: elasticsearch:nori
    ports:
      - "9200:9200"
    environment:
      # 단일 노드 모드
      - discovery.type=single-node
      # 보안기능 비활설화 -> 운영시는 켜야함
      # - xpack.security.enabled=false